### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by szymmirr** [Royalgamer06/steam-free-apps#2] opened 2017-04-24 13:52 UTC
Got an error after running bat.exe, I followed all the steps

module.js:471
    throw err;
    ^

Error: Cannot find module 'steam-user'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Pobrane\steam-free-packages-master\main.js:2:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by YeAhxxx** [comment] 2017-04-24 14:00
"Error: Cannot find module 'steam-user'" It simply means it can't find the required module to run.

Try this command "npm install steam-user"
Run as admin if needed.

**Comment by szymmirr** [comment] 2017-04-24 14:14
I see install.bat is supposed to do it, so doing it manually doesn't change anything. All done as admin.

**Comment by ghost** [comment] 2017-04-24 14:22
Try installing lines from install.bat in Windows PowerShell. I don't know but somehow it worked for me.

**Comment by ghost** [comment] 2017-04-24 14:26
Also I get new error now:

$ = require("jquery")(jsdom.jsdom().defaultView),
                            ^

TypeError: jsdom.jsdom is not a function
    at Object.<anonymous> (C:\Users\Nikola Perovic\Desktop\steam-free-packages-master\main.js:5:29)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3

**Comment by szymmirr** [comment] 2017-04-24 17:48
It seems like a problem with NodeJS itself, anyway, I managed to run it from second OS... but it only gets worse

<--- Last few GCs --->

[2396:002AB900]       11 ms: Mark-sweep 0.7 (3.6) -> 0.6 (3.6) MB, 0.6 / 0.0 ms
 deserialize GC in old space requested
[2396:002AB900]       12 ms: Mark-sweep 0.7 (3.6) -> 0.6 (3.6) MB, 0.6 / 0.0 ms
 deserialize GC in old space requested
[2396:002AB900]       13 ms: Mark-sweep 0.7 (3.6) -> 0.6 (3.6) MB, 0.5 / 0.0 ms
 deserialize GC in old space requested
[2396:002AB900]       13 ms: Mark-sweep 0.7 (3.6) -> 0.6 (3.6) MB, 0.5 / 0.0 ms
 deserialize GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: deserialize context Allocation failed - process out of memory

**Comment by Revadike** [comment] 2017-04-25 00:21
If anyone has issues installing npm modules, you can always try to manually download them (from github) and extract them to your node_modules folder. 

Also, I'd prefer if everyone creates a separate issue if your issue is different. This shouldn't be a general troubleshooting topic. Each (similar) issues needs their own issue ticket. It also needs to have a better / more specific title. "Error" is probably the vaguest title you can choose.

@szymmirr Are you running run.bat? It should assign 8 GB of RAM usage to the process. That should be enough to say the least. I don't know why it uses so many memory. If it's caused by my code, I'll have to fix that.

**Comment by jakey1995abc** [comment] 2017-04-28 22:26
A fix for this issue is to manually install each package into cmd whilst running it as an admin. Just run cmd as admin and copy/paste the following:

npm install steamauth
npm install steam-user
npm install steamcommunity
npm install jsdom
npm install fs
npm install request
npm install cloudscraper

This should install them to C:\WINDOWS\System32\node_modules.
Then run run.bat as admin.
After these steps I stopped getting the errors described in the original post but started getting these errors instead: "TypeError: jsdom.jsdom is not a function" #5 
I hope this some how helps :D

**Comment by gamikace** [comment] 2017-04-30 17:11
I got an error :(

 module.js:327
    throw err;
    ^

Error: Cannot find module 'C:\WINDOWS\system32\main.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

**Comment by Revadike** [comment] 2017-05-02 14:09
Use the new install.bat. It is fixed now 👍

**Closed as completed** 2017-05-02 14:10 UTC
